# Generated by Django 4.1.4 on 2022-12-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='facilities',
            field=models.ManyToManyField(default=None, related_name='hotels', to='residences.facility'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='policies',
            field=models.ManyToManyField(default=None, related_name='hotels', to='residences.policy'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='units',
            field=models.ManyToManyField(default=None, related_name='hotels', to='residences.unit'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='facilities',
            field=models.ManyToManyField(default=None, related_name='units', to='residences.facility'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='policies',
            field=models.ManyToManyField(default=None, related_name='units', to='residences.policy'),
        ),
    ]
