# Generated by Django 4.1.4 on 2022-12-22 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentresidence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_residence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='renthotel',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented_days', to='residences.unit'),
        ),
        migrations.AddField(
            model_name='renthotel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_hotel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='residence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='residences.residence'),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='residences.unit'),
        ),
        migrations.AddField(
            model_name='policy',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='residences.hotel'),
        ),
        migrations.AddField(
            model_name='policy',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='residences.residence'),
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_album', to='residences.hotel'),
        ),
        migrations.AddField(
            model_name='imagealbum',
            name='residence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_album', to='residences.residence'),
        ),
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='residences.imagealbum'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='residences.city'),
        ),
        migrations.AddField(
            model_name='facility',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='residences.hotel'),
        ),
        migrations.AddField(
            model_name='facility',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='residences.residence'),
        ),
        migrations.AddField(
            model_name='facility',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='residences.unit'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='residences.country'),
        ),
        migrations.AlterUniqueTogether(
            name='rentresidence',
            unique_together={('date', 'residence')},
        ),
        migrations.AlterUniqueTogether(
            name='renthotel',
            unique_together={('date', 'unit')},
        ),
    ]
