# Generated by Django 4.1.4 on 2022-12-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='price_info',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='price_info',
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='residence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='residences.residence'),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='residences.unit'),
        ),
    ]
