# Generated by Django 4.1.4 on 2022-12-22 11:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_remove_residence_price_info_remove_unit_price_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentResidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2022, 12, 22, 15, 2, 17, 480454))),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('residence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residences.residence')),
            ],
            options={
                'unique_together': {('date', 'residence')},
            },
        ),
    ]
