# Generated by Django 4.1.4 on 2022-12-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidencePriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(default=2)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('residence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='residences.residence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnitPriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(default=2)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='residences.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PriceInfo',
        ),
    ]
