# Generated by Django 4.1.4 on 2022-12-22 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_rentresidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentresidence',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 22)),
        ),
        migrations.AlterField(
            model_name='rentresidence',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residences.residence'),
        ),
    ]
