# Generated by Django 4.1.4 on 2022-12-28 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_residencepriceinfo_unitpriceinfo_delete_priceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='%(class)ss')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='residence',
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('abstractimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residences.abstractimage')),
                ('hotel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_album', to='residences.hotel')),
            ],
            bases=('residences.abstractimage',),
        ),
        migrations.CreateModel(
            name='ResidenceImage',
            fields=[
                ('abstractimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='residences.abstractimage')),
                ('residence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_album', to='residences.residence')),
            ],
            bases=('residences.abstractimage',),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageAlbum',
        ),
    ]
