# Generated by Django 4.1.4 on 2023-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_currencyexchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthotel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentresidence',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
