# Generated by Django 4.1.4 on 2022-12-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0004_alter_rentresidence_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentresidence',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rented_days', to='residences.residence'),
        ),
    ]
