# Generated by Django 4.1.4 on 2022-12-28 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0006_hotelpolicy_residencepolicy_delete_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_album', to='residences.hotel'),
        ),
        migrations.AlterField(
            model_name='renthotel',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 28)),
        ),
        migrations.AlterField(
            model_name='rentresidence',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 28)),
        ),
        migrations.AlterField(
            model_name='residenceimage',
            name='residence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_album', to='residences.residence'),
        ),
    ]
