# Generated by Django 4.1.4 on 2022-12-22 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residences', '0006_rentresidence_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentresidence',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_residence', to=settings.AUTH_USER_MODEL),
        ),
    ]
