# Generated by Django 4.1.4 on 2022-12-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0007_alter_hotelimage_hotel_alter_renthotel_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentresidence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rentresidence',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='rentresidence',
            name='user',
        ),
        migrations.AlterField(
            model_name='residencepriceinfo',
            name='weekday',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='unitpriceinfo',
            name='weekday',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='RentHotel',
        ),
        migrations.DeleteModel(
            name='RentResidence',
        ),
    ]
