# Generated by Django 4.1.4 on 2022-12-31 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0009_rentresidence_renthotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renthotel',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 31)),
        ),
        migrations.AlterField(
            model_name='rentresidence',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 31)),
        ),
        migrations.AlterField(
            model_name='residencepriceinfo',
            name='weekday',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='unitpriceinfo',
            name='weekday',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
