# Generated by Django 4.1.4 on 2023-01-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencerating',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='residences.residence'),
        ),
    ]
