# Generated by Django 4.1.4 on 2023-01-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('residences', '0001_initial'),
        ('tickets', '0001_initial'),
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residencerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residencecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.residencecomment'),
        ),
        migrations.AddField(
            model_name='residencecomment',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='residences.residence'),
        ),
        migrations.AddField(
            model_name='residencecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelrating',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='residences.hotel'),
        ),
        migrations.AddField(
            model_name='hotelrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotelcomment',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='residences.hotel'),
        ),
        migrations.AddField(
            model_name='hotelcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.hotelcomment'),
        ),
        migrations.AddField(
            model_name='hotelcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplaneticketrating',
            name='airplane_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='tickets.airplaneticket'),
        ),
        migrations.AddField(
            model_name='airplaneticketrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplaneticketcomment',
            name='airplane_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.airplaneticket'),
        ),
        migrations.AddField(
            model_name='airplaneticketcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.airplaneticketcomment'),
        ),
        migrations.AddField(
            model_name='airplaneticketcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='residencerating',
            unique_together={('user', 'residence')},
        ),
        migrations.AlterUniqueTogether(
            name='hotelrating',
            unique_together={('user', 'hotel')},
        ),
        migrations.AlterUniqueTogether(
            name='airplaneticketrating',
            unique_together={('user', 'airplane_ticket')},
        ),
    ]
