# Generated by Django 4.1.4 on 2022-12-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_residences', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rentresidence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rentresidence',
            name='residence',
        ),
        migrations.RemoveField(
            model_name='rentresidence',
            name='user',
        ),
        migrations.DeleteModel(
            name='RentHotel',
        ),
        migrations.DeleteModel(
            name='RentResidence',
        ),
    ]
