# Generated by Django 4.1.4 on 2023-01-03 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyairplaneticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airplane_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplaneticketpriceinfo',
            name='airplane_ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='tickets.airplaneticket'),
        ),
        migrations.AddField(
            model_name='airplaneticketpriceinfo',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='residences.currency'),
        ),
        migrations.AddField(
            model_name='airplaneticketpolicy',
            name='airplane_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='tickets.airplaneticket'),
        ),
        migrations.AddField(
            model_name='airplaneticketfacility',
            name='airplane_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='tickets.airplaneticket'),
        ),
        migrations.AddField(
            model_name='airplaneticket',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_arrival', to='tickets.terminal'),
        ),
        migrations.AddField(
            model_name='airplaneticket',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_departure', to='tickets.terminal'),
        ),
    ]
