# Generated by Django 4.1.4 on 2022-12-28 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyairplaneticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airplane_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airplaneticket',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_arrival', to='tickets.terminal'),
        ),
        migrations.AddField(
            model_name='airplaneticket',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_departure', to='tickets.terminal'),
        ),
    ]
