# Generated by Django 4.1.4 on 2022-12-24 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_airplaneticket_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplaneticket',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss_arrival', to='tickets.terminal'),
        ),
    ]
