# Generated by Django 4.1.4 on 2022-12-31 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_airplaneticketpolicy_delete_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirPlaneTicketPriceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(default=5)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('airplane_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='tickets.airplaneticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='PriceInfo',
        ),
    ]
