# Generated by Django 4.1.4 on 2022-12-24 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0006_remove_airplaneticket_date_alter_airplaneticket_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyAirPlaneTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(default=1)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_tickets', to='tickets.airplaneticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airplane_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
